In [1]:
import numpy as np

In [ ]:
##        inicio, fim, passo = [incio, fim[
np.arange(     5,  20,   3)

array([ 5,  8, 11, 14, 17])

In [ ]:
##        inicio, fim + passo/2, passo = [incio, fim]
np.arange(     5,  20 + 3/2,   3)

array([ 5.,  8., 11., 14., 17., 20.])

In [ ]:
##          inicio, fim, numero de pontos = [incio, fim]
np.linspace(     5,  20,    5)

array([ 5.  ,  8.75, 12.5 , 16.25, 20.  ])

In [17]:
##          inicio, fim, numero de pontos = [incio, fim[
np.linspace(     5,  20,    5, endpoint=False)

array([ 5.,  8., 11., 14., 17.])

In [ ]:
dt = 0.2

t = np.arange(0, 100*dt, dt)

print(t)

[ 0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6
  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4
  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2
  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.
 11.2 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8
 14.  14.2 14.4 14.6 14.8 15.  15.2 15.4 15.6 15.8 16.  16.2 16.4 16.6
 16.8 17.  17.2 17.4 17.6 17.8 18.  18.2 18.4 18.6 18.8 19.  19.2 19.4
 19.6 19.8]


In [12]:
v = np.zeros(5)
v[0] = 1
v

array([1., 0., 0., 0., 0.])